version: '3.8'

services:

  db:
    image: mysql
    container_name: db_docker_symfony
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      - dev

  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    restart: always
    volumes:
      - ./app:/var/www
    environment:
      - APP_ENV=prod
      - APP_DEBUG=0
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: